# Generated by Django 4.0.3 on 2022-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=14)),
                ('flat_buy', models.BooleanField(default=False)),
                ('flat_rent', models.BooleanField(default=False)),
                ('flat_type', models.CharField(max_length=10)),
                ('pool', models.CharField(max_length=20)),
                ('gym', models.CharField(max_length=20)),
                ('creche', models.CharField(max_length=20)),
                ('member', models.IntegerField(default=0)),
                ('furnished', models.BooleanField(default=False)),
            ],
        ),
    ]
