# Generated by Django 4.0.3 on 2022-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='furnished',
        ),
        migrations.AddField(
            model_name='guest',
            name='flat_size',
            field=models.CharField(default='1 BHK', max_length=20),
        ),
    ]
