# Generated by Django 4.0.3 on 2022-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_guest_furnished_guest_flat_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='flat_size',
            field=models.CharField(max_length=20),
        ),
    ]
