# Generated by Django 4.0.3 on 2022-04-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_guest_flat_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='flat_type',
            new_name='furnished',
        ),
    ]
