# Generated by Django 4.0.3 on 2022-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_flat_type_guest_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='furnished',
            field=models.CharField(max_length=100),
        ),
    ]
