# Generated by Django 4.0.3 on 2022-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_guest_furnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
