# Generated by Django 4.0.3 on 2022-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('gender', models.SlugField(max_length=25)),
                ('mobile', models.IntegerField(default=0)),
                ('place', models.CharField(default='none', max_length=100)),
                ('dateTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AlterField(
            model_name='guest',
            name='creche',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gym',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='pool',
            field=models.BooleanField(null=True),
        ),
    ]
